import type { MenuItem } from './menuTypes';

export const DEFAULT_MENU_ITEMS: MenuItem[] = [
  {
    id: 'protein-chicken',
    name: 'Chicken',
    category: 'protein',
    description: 'Grilled hibachi chicken',
    pricePerServing: 26,
    costPerServing: 3.5,
    isAvailable: true,
    dietaryTags: [],
    allergens: [],
  },
  {
    id: 'protein-steak',
    name: 'Steak',
    category: 'protein',
    description: 'Premium hibachi steak',
    pricePerServing: 34,
    costPerServing: 6,
    isAvailable: true,
    dietaryTags: [],
    allergens: [],
  },
  {
    id: 'protein-shrimp',
    name: 'Shrimp',
    category: 'protein',
    description: 'Grilled hibachi shrimp',
    pricePerServing: 32,
    costPerServing: 5,
    isAvailable: true,
    dietaryTags: [],
    allergens: ['shellfish'],
  },
  {
    id: 'protein-scallops',
    name: 'Scallops',
    category: 'protein',
    description: 'Seared hibachi scallops',
    pricePerServing: 38,
    costPerServing: 7,
    isAvailable: true,
    dietaryTags: [],
    allergens: ['shellfish'],
  },
  {
    id: 'side-rice',
    name: 'Fried Rice',
    category: 'side',
    description: 'Classic hibachi fried rice',
    pricePerServing: 4,
    costPerServing: 1,
    isAvailable: true,
    dietaryTags: [],
    allergens: ['eggs', 'soy'],
  },
  {
    id: 'side-noodles',
    name: 'Noodles',
    category: 'side',
    description: 'Hibachi noodles',
    pricePerServing: 4,
    costPerServing: 1,
    isAvailable: true,
    dietaryTags: [],
    allergens: ['gluten', 'soy'],
  },
  {
    id: 'side-salad',
    name: 'Side Salad',
    category: 'side',
    description: 'Fresh garden salad with ginger dressing',
    pricePerServing: 3,
    costPerServing: 0.75,
    isAvailable: true,
    dietaryTags: ['vegetarian'],
    allergens: [],
  },
  {
    id: 'side-veggies',
    name: 'Mixed Vegetables',
    category: 'side',
    description: 'Grilled seasonal vegetables',
    pricePerServing: 4,
    costPerServing: 1.25,
    isAvailable: true,
    dietaryTags: ['vegetarian', 'vegan'],
    allergens: [],
  },
];
